//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_scenariya
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ежик.
    /// </summary>
    // *** Start programmer edit section *** (Ежик CustomAttributes)

    // *** End programmer edit section *** (Ежик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЕжикE", new string[] {
            "Имя as \'Имя\'",
            "Возраст as \'Возраст\'"})]
    [AssociatedDetailViewAttribute("ЕжикE", "ЛапаЕжика", "ЛапаЕжикаE", true, "", "Лапа ежика", true, new string[] {
            ""})]
    [View("ЕжикL", new string[] {
            "Имя as \'Имя\'",
            "Возраст as \'Возраст\'"})]
    public class Ежик : ICSSoft.STORMNET.DataObject
    {

        private int fВозраст;

        private string fИмя;

        private IIS.Proekt_scenariya.DetailArrayOfЛапаЕжика fЛапаЕжика;

        // *** Start programmer edit section *** (Ежик CustomMembers)

        // *** End programmer edit section *** (Ежик CustomMembers)


        /// <summary>
        /// Возраст.
        /// </summary>
        // *** Start programmer edit section *** (Ежик.Возраст CustomAttributes)

        // *** End programmer edit section *** (Ежик.Возраст CustomAttributes)
        public virtual int Возраст
        {
            get
            {
                // *** Start programmer edit section *** (Ежик.Возраст Get start)

                // *** End programmer edit section *** (Ежик.Возраст Get start)
                int result = this.fВозраст;
                // *** Start programmer edit section *** (Ежик.Возраст Get end)

                // *** End programmer edit section *** (Ежик.Возраст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ежик.Возраст Set start)

                // *** End programmer edit section *** (Ежик.Возраст Set start)
                this.fВозраст = value;
                // *** Start programmer edit section *** (Ежик.Возраст Set end)

                // *** End programmer edit section *** (Ежик.Возраст Set end)
            }
        }

        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Ежик.Имя CustomAttributes)

        // *** End programmer edit section *** (Ежик.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Ежик.Имя Get start)

                // *** End programmer edit section *** (Ежик.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Ежик.Имя Get end)

                // *** End programmer edit section *** (Ежик.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ежик.Имя Set start)

                // *** End programmer edit section *** (Ежик.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Ежик.Имя Set end)

                // *** End programmer edit section *** (Ежик.Имя Set end)
            }
        }

        /// <summary>
        /// Ежик.
        /// </summary>
        // *** Start programmer edit section *** (Ежик.ЛапаЕжика CustomAttributes)

        // *** End programmer edit section *** (Ежик.ЛапаЕжика CustomAttributes)
        public virtual IIS.Proekt_scenariya.DetailArrayOfЛапаЕжика ЛапаЕжика
        {
            get
            {
                // *** Start programmer edit section *** (Ежик.ЛапаЕжика Get start)

                // *** End programmer edit section *** (Ежик.ЛапаЕжика Get start)
                if ((this.fЛапаЕжика == null))
                {
                    this.fЛапаЕжика = new IIS.Proekt_scenariya.DetailArrayOfЛапаЕжика(this);
                }
                IIS.Proekt_scenariya.DetailArrayOfЛапаЕжика result = this.fЛапаЕжика;
                // *** Start programmer edit section *** (Ежик.ЛапаЕжика Get end)

                // *** End programmer edit section *** (Ежик.ЛапаЕжика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ежик.ЛапаЕжика Set start)

                // *** End programmer edit section *** (Ежик.ЛапаЕжика Set start)
                this.fЛапаЕжика = value;
                // *** Start programmer edit section *** (Ежик.ЛапаЕжика Set end)

                // *** End programmer edit section *** (Ежик.ЛапаЕжика Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ЕжикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕжикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕжикE", typeof(IIS.Proekt_scenariya.Ежик));
                }
            }

            /// <summary>
            /// "ЕжикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕжикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕжикL", typeof(IIS.Proekt_scenariya.Ежик));
                }
            }
        }
    }
}

