//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_scenariya
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Лапа ежика.
    /// </summary>
    // *** Start programmer edit section *** (ЛапаЕжика CustomAttributes)

    // *** End programmer edit section *** (ЛапаЕжика CustomAttributes)
    [AutoAltered()]
    [Caption("Лапа ежика")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛапаЕжикаE", new string[] {
            "Расположение as \'Расположение\'",
            "Целостность as \'Целостность\'"})]
    public class ЛапаЕжика : ICSSoft.STORMNET.DataObject
    {

        private string fРасположение;

        private bool fЦелостность;

        private IIS.Proekt_scenariya.Ежик fЕжик;

        // *** Start programmer edit section *** (ЛапаЕжика CustomMembers)

        // *** End programmer edit section *** (ЛапаЕжика CustomMembers)


        /// <summary>
        /// Расположение.
        /// </summary>
        // *** Start programmer edit section *** (ЛапаЕжика.Расположение CustomAttributes)

        // *** End programmer edit section *** (ЛапаЕжика.Расположение CustomAttributes)
        [StrLen(255)]
        public virtual string Расположение
        {
            get
            {
                // *** Start programmer edit section *** (ЛапаЕжика.Расположение Get start)

                // *** End programmer edit section *** (ЛапаЕжика.Расположение Get start)
                string result = this.fРасположение;
                // *** Start programmer edit section *** (ЛапаЕжика.Расположение Get end)

                // *** End programmer edit section *** (ЛапаЕжика.Расположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛапаЕжика.Расположение Set start)

                // *** End programmer edit section *** (ЛапаЕжика.Расположение Set start)
                this.fРасположение = value;
                // *** Start programmer edit section *** (ЛапаЕжика.Расположение Set end)

                // *** End programmer edit section *** (ЛапаЕжика.Расположение Set end)
            }
        }

        /// <summary>
        /// Целостность.
        /// </summary>
        // *** Start programmer edit section *** (ЛапаЕжика.Целостность CustomAttributes)

        // *** End programmer edit section *** (ЛапаЕжика.Целостность CustomAttributes)
        public virtual bool Целостность
        {
            get
            {
                // *** Start programmer edit section *** (ЛапаЕжика.Целостность Get start)

                // *** End programmer edit section *** (ЛапаЕжика.Целостность Get start)
                bool result = this.fЦелостность;
                // *** Start programmer edit section *** (ЛапаЕжика.Целостность Get end)

                // *** End programmer edit section *** (ЛапаЕжика.Целостность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛапаЕжика.Целостность Set start)

                // *** End programmer edit section *** (ЛапаЕжика.Целостность Set start)
                this.fЦелостность = value;
                // *** Start programmer edit section *** (ЛапаЕжика.Целостность Set end)

                // *** End programmer edit section *** (ЛапаЕжика.Целостность Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proekt_scenariya.Ежик.
        /// </summary>
        // *** Start programmer edit section *** (ЛапаЕжика.Ежик CustomAttributes)

        // *** End programmer edit section *** (ЛапаЕжика.Ежик CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Ежик"})]
        public virtual IIS.Proekt_scenariya.Ежик Ежик
        {
            get
            {
                // *** Start programmer edit section *** (ЛапаЕжика.Ежик Get start)

                // *** End programmer edit section *** (ЛапаЕжика.Ежик Get start)
                IIS.Proekt_scenariya.Ежик result = this.fЕжик;
                // *** Start programmer edit section *** (ЛапаЕжика.Ежик Get end)

                // *** End programmer edit section *** (ЛапаЕжика.Ежик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛапаЕжика.Ежик Set start)

                // *** End programmer edit section *** (ЛапаЕжика.Ежик Set start)
                this.fЕжик = value;
                // *** Start programmer edit section *** (ЛапаЕжика.Ежик Set end)

                // *** End programmer edit section *** (ЛапаЕжика.Ежик Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ЛапаЕжикаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛапаЕжикаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛапаЕжикаE", typeof(IIS.Proekt_scenariya.ЛапаЕжика));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of ЛапаЕжика.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЛапаЕжика CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЛапаЕжика CustomAttributes)
    public class DetailArrayOfЛапаЕжика : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (IIS.Proekt_scenariya.DetailArrayOfЛапаЕжика members)

        // *** End programmer edit section *** (IIS.Proekt_scenariya.DetailArrayOfЛапаЕжика members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЛапаЕжика by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЛапаЕжика.
        /// </summary>
        public DetailArrayOfЛапаЕжика(IIS.Proekt_scenariya.Ежик fЕжик) : 
                base(typeof(ЛапаЕжика), ((ICSSoft.STORMNET.DataObject)(fЕжик)))
        {
        }

        public IIS.Proekt_scenariya.ЛапаЕжика this[int index]
        {
            get
            {
                return ((IIS.Proekt_scenariya.ЛапаЕжика)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(IIS.Proekt_scenariya.ЛапаЕжика dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

