//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_scenariya
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Нора ежика.
    /// </summary>
    // *** Start programmer edit section *** (НораЕжика CustomAttributes)

    // *** End programmer edit section *** (НораЕжика CustomAttributes)
    [AutoAltered()]
    [Caption("Нора ежика")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НораЕжикаE", new string[] {
            "Расположение as \'Расположение\'",
            "КоличествоВходов as \'Количество входов\'",
            "Ежик as \'Ежик\'",
            "Ежик.Имя as \'Имя\'"}, Hidden=new string[] {
            "Ежик.Имя"})]
    [MasterViewDefineAttribute("НораЕжикаE", "Ежик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("НораЕжикаL", new string[] {
            "Расположение as \'Расположение\'",
            "КоличествоВходов as \'Количество входов\'",
            "Ежик.Имя as \'Имя\'"})]
    public class НораЕжика : ICSSoft.STORMNET.DataObject
    {

        private int fКоличествоВходов;

        private string fРасположение;

        private IIS.Proekt_scenariya.Ежик fЕжик;

        // *** Start programmer edit section *** (НораЕжика CustomMembers)

        // *** End programmer edit section *** (НораЕжика CustomMembers)


        /// <summary>
        /// КоличествоВходов.
        /// </summary>
        // *** Start programmer edit section *** (НораЕжика.КоличествоВходов CustomAttributes)

        // *** End programmer edit section *** (НораЕжика.КоличествоВходов CustomAttributes)
        public virtual int КоличествоВходов
        {
            get
            {
                // *** Start programmer edit section *** (НораЕжика.КоличествоВходов Get start)

                // *** End programmer edit section *** (НораЕжика.КоличествоВходов Get start)
                int result = this.fКоличествоВходов;
                // *** Start programmer edit section *** (НораЕжика.КоличествоВходов Get end)

                // *** End programmer edit section *** (НораЕжика.КоличествоВходов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НораЕжика.КоличествоВходов Set start)

                // *** End programmer edit section *** (НораЕжика.КоличествоВходов Set start)
                this.fКоличествоВходов = value;
                // *** Start programmer edit section *** (НораЕжика.КоличествоВходов Set end)

                // *** End programmer edit section *** (НораЕжика.КоличествоВходов Set end)
            }
        }

        /// <summary>
        /// Расположение.
        /// </summary>
        // *** Start programmer edit section *** (НораЕжика.Расположение CustomAttributes)

        // *** End programmer edit section *** (НораЕжика.Расположение CustomAttributes)
        [StrLen(255)]
        public virtual string Расположение
        {
            get
            {
                // *** Start programmer edit section *** (НораЕжика.Расположение Get start)

                // *** End programmer edit section *** (НораЕжика.Расположение Get start)
                string result = this.fРасположение;
                // *** Start programmer edit section *** (НораЕжика.Расположение Get end)

                // *** End programmer edit section *** (НораЕжика.Расположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НораЕжика.Расположение Set start)

                // *** End programmer edit section *** (НораЕжика.Расположение Set start)
                this.fРасположение = value;
                // *** Start programmer edit section *** (НораЕжика.Расположение Set end)

                // *** End programmer edit section *** (НораЕжика.Расположение Set end)
            }
        }

        /// <summary>
        /// Нора ежика.
        /// </summary>
        // *** Start programmer edit section *** (НораЕжика.Ежик CustomAttributes)

        // *** End programmer edit section *** (НораЕжика.Ежик CustomAttributes)
        [PropertyStorage(new string[] {
                "Ежик"})]
        [NotNull()]
        public virtual IIS.Proekt_scenariya.Ежик Ежик
        {
            get
            {
                // *** Start programmer edit section *** (НораЕжика.Ежик Get start)

                // *** End programmer edit section *** (НораЕжика.Ежик Get start)
                IIS.Proekt_scenariya.Ежик result = this.fЕжик;
                // *** Start programmer edit section *** (НораЕжика.Ежик Get end)

                // *** End programmer edit section *** (НораЕжика.Ежик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НораЕжика.Ежик Set start)

                // *** End programmer edit section *** (НораЕжика.Ежик Set start)
                this.fЕжик = value;
                // *** Start programmer edit section *** (НораЕжика.Ежик Set end)

                // *** End programmer edit section *** (НораЕжика.Ежик Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "НораЕжикаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НораЕжикаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НораЕжикаE", typeof(IIS.Proekt_scenariya.НораЕжика));
                }
            }

            /// <summary>
            /// "НораЕжикаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НораЕжикаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НораЕжикаL", typeof(IIS.Proekt_scenariya.НораЕжика));
                }
            }
        }
    }
}

